### ISSUE TITLE
Parsing of nested arrays of objects results in empty array

### ISSUE THREAD

**Issue by klahdenk** [hash-bang/bfj-collections#1]
It seems that nested arrays of objects are not parsed properly.

Test data: [{"foo": "bar", "foo2": [1,2,3], "baz": [{"foo":"bar"}]}]

Expected result: property "baz" would have one object in it
Actual result: "baz" is an empty array

The nested array of numbers seems to work fine, though and "foo2" is parsed correctly.
example code snippet to reproduce:

var stream = fs.createReadStream("test.json", {encoding: 'utf8'});
bfjc(stream)
  .on('bfjc', data => {
    console.log(data);
  })
  .on(bfj.events.end, () => {

  })

**Comment by hash-bang** [comment]
This took a bit of tracking down. Turns out the root element and the sub-element object closures need to be dealt with seperately.

Should be working in the new version now.

Thanks for the report.
